---
abstract: "tests 'meta/changes.ttl' is up to date"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::RDF::DOAP::Version
name: Test-RDF-DOAP-Version
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  RDF::TriN3: 0.202
  RDF::Trine: 0.135
  Test::More: 0
  URI::Escape: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Test-RDF-DOAP-Version
  homepage: https://metacpan.org/release/Test-RDF-DOAP-Version
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-test-rdf-doap-version
version: 0.008
